"""Prometheus metrics — exposed on :8001/metrics."""
from __future__ import annotations

from prometheus_client import Counter, Gauge, Histogram, start_http_server

# --- Counters ---
queries_generated = Counter(
    "collection_queries_generated_total",
    "Total queries generated by the query agent",
    ["run_id"],
)
queries_kept = Counter(
    "collection_queries_kept_total",
    "Queries kept after relevance filtering",
    ["run_id"],
)
urls_discovered = Counter(
    "collection_urls_discovered_total",
    "URLs discovered from search backends",
    ["run_id", "backend"],
)
docs_saved = Counter(
    "collection_docs_saved_total",
    "Documents successfully scraped and saved",
    ["run_id"],
)
failures_total = Counter(
    "collection_failures_total",
    "Pipeline failures by stage and error type",
    ["run_id", "stage", "error_type"],
)

# --- Gauges ---
run_active = Gauge(
    "collection_run_active",
    "1 if a collection run is in progress, 0 otherwise",
)
urls_pending = Gauge(
    "collection_urls_pending",
    "URLs remaining in the scrape queue",
    ["run_id"],
)
circuit_breaker_state = Gauge(
    "circuit_breaker_state",
    "Circuit breaker state: 0=closed 1=open 2=half_open",
    ["backend"],
)

# --- Histograms ---
scrape_duration = Histogram(
    "collection_scrape_duration_seconds",
    "Time to scrape a single URL",
    ["run_id"],
    buckets=[0.5, 1, 2, 5, 10, 20, 30, 60],
)
stage_duration = Histogram(
    "collection_stage_duration_seconds",
    "Time to complete a pipeline stage",
    ["run_id", "stage"],
    buckets=[1, 5, 15, 30, 60, 120, 300, 600, 1200],
)
rate_limit_wait = Histogram(
    "rate_limit_wait_seconds",
    "Time spent waiting for rate limiter",
    ["backend"],
    buckets=[0.01, 0.05, 0.1, 0.5, 1, 2, 5],
)


class PipelineMetrics:
    """Convenience wrapper for recording per-run metrics."""

    def __init__(self, run_id: str) -> None:
        self.run_id = run_id

    def inc_queries_generated(self, count: int = 1) -> None:
        queries_generated.labels(run_id=self.run_id).inc(count)

    def inc_queries_kept(self, count: int = 1) -> None:
        queries_kept.labels(run_id=self.run_id).inc(count)

    def inc_urls_discovered(self, backend: str, count: int = 1) -> None:
        urls_discovered.labels(run_id=self.run_id, backend=backend).inc(count)

    def inc_docs_saved(self, count: int = 1) -> None:
        docs_saved.labels(run_id=self.run_id).inc(count)

    def inc_failure(self, stage: str, error_type: str) -> None:
        failures_total.labels(run_id=self.run_id, stage=stage, error_type=error_type).inc()

    def observe_scrape(self, duration_s: float) -> None:
        scrape_duration.labels(run_id=self.run_id).observe(duration_s)

    def observe_stage(self, stage: str, duration_s: float) -> None:
        stage_duration.labels(run_id=self.run_id, stage=stage).observe(duration_s)


def start_metrics_server(port: int = 8001) -> None:
    start_http_server(port)
