use_default_settings: true

general:
  debug: false
  instance_name: "collection-searxng"

server:
  secret_key: "llmfactory-searxng-secret"
  bind_address: "0.0.0.0"
  limiter: false
  image_proxy: false

search:
  safe_search: 0
  autocomplete: ""
  default_lang: "en"
  formats:
    - html
    - json
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

ui:
  static_use_hash: true

outgoing:
  request_timeout: 10.0
  max_request_timeout: 15.0
  pool_connections: 100
  pool_maxsize: 20

engines:
  - name: google
    engine: google
    disabled: false
    timeout: 8.0
  - name: bing
    engine: bing
    disabled: false
    timeout: 8.0
  - name: duckduckgo
    engine: duckduckgo
    disabled: false
    timeout: 8.0
  - name: brave
    engine: brave
    disabled: false
    timeout: 8.0
  - name: wikipedia
    engine: wikipedia
    disabled: false
    timeout: 5.0
